@echo off
cd /d %~dp0backend
echo [Backend] Starting...
if not exist venv (
    echo [Backend] Creating venv...
    python -m venv venv
)
call venv\Scripts\activate.bat
echo [Backend] Installing dependencies...
pip install -q -r requirements.txt
echo [Backend] Starting API on port 8000...
uvicorn app.main:app --reload --host 127.0.0.1 --port 8000
pause
