@echo off
cd /d %~dp0parser_service
echo [Parser] Starting...
if not exist venv (
    echo [Parser] Creating venv...
    python -m venv venv
)
call venv\Scripts\activate.bat
echo [Parser] Installing dependencies...
pip install -q -r requirements.txt
echo [Parser] Installing Playwright...
playwright install chromium
echo [Parser] Starting API on port 9003...
python run_api.py
pause
