# Скрипт для установки pre-commit hook
# Использование: .\scripts\setup-pre-commit.ps1

$ProjectRoot = Split-Path -Parent $PSScriptRoot
$GitHooksDir = Join-Path $ProjectRoot ".git\hooks"
$PreCommitHook = Join-Path $GitHooksDir "pre-commit"
$PreCommitScript = Join-Path $ProjectRoot "scripts\pre-commit.ps1"

Write-Host "Setting up pre-commit hook..." -ForegroundColor Cyan

# Проверка наличия .git директории
if (-not (Test-Path (Join-Path $ProjectRoot ".git"))) {
    Write-Host "❌ .git directory not found. Is this a git repository?" -ForegroundColor Red
    exit 1
}

# Создание директории hooks, если не существует
if (-not (Test-Path $GitHooksDir)) {
    New-Item -ItemType Directory -Path $GitHooksDir -Force | Out-Null
    Write-Host "Created .git\hooks directory" -ForegroundColor Green
}

# Создание pre-commit hook
$hookContent = @"
# Pre-commit hook
# Generated by setup-pre-commit.ps1
powershell.exe -ExecutionPolicy Bypass -File "$PreCommitScript"
exit `$LASTEXITCODE
"@

$hookContent | Out-File -FilePath $PreCommitHook -Encoding UTF8 -NoNewline
Write-Host "Created pre-commit hook" -ForegroundColor Green

# Установка прав на выполнение (для Unix-подобных систем)
if ($IsLinux -or $IsMacOS) {
    chmod +x $PreCommitHook
    Write-Host "Set execute permissions" -ForegroundColor Green
}

Write-Host "`n✅ Pre-commit hook installed successfully!" -ForegroundColor Green
Write-Host "The hook will run automatically before each commit." -ForegroundColor Yellow
Write-Host "To test: git commit (will trigger the hook)" -ForegroundColor Yellow











